/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.learn.starter;

import org.springframework.util.StringUtils;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class App {

    private String name;
    private int age;

    public static void main(String[] args) {
       System.out.println(StringUtils.capitalize("hello world"));
    }
}
